# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170207_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('correo_electronico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('clasificacion_taxonomica', models.CharField(max_length=200)),
                ('descripcion_corta', models.CharField(max_length=200)),
                ('descripcion_larga', models.CharField(max_length=500)),
                ('fotoFile', models.ImageField(null=True, upload_to='images')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Especie'),
        ),
    ]
